name: Build GitHub pages

on:
    push:
        branches: [ main ]

jobs:
    pages:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   uses: actions/checkout@v3
                with:
                    ref: gh-pages
                    path: build.1
            -   run: npm ci
            -   run: npm run build
            -   working-directory: ./build
                run: |
                    MESSAGE=$(git log -1 --format="sync: [%h] %s")
                    mv ../build.1/.git ./.git
                    git config user.name 'github-actions[bot]'
                    git config user.email 'github-actions[bot]@users.noreply.github.com'
                    git add .
                    git commit -m "$MESSAGE"
                    git push origin gh-pages --force